services:
  api:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # DBを使わないなら以下を削除またはコメントアウト
      # SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/app
      # SPRING_DATASOURCE_USERNAME: app
      # SPRING_DATASOURCE_PASSWORD: app
    depends_on:
      - dynamodb
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
