spring:
  application:
    name: authjava
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
      hibernate: WARN
      security: DEBUG
server:
  servlet:
    session:
      cookie:
        same-site: lax
